[package]
name = "oxbow"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "../README.md"
description = "Read specialized bioinformatic file formats as data frames in R, Python, and more."

[dependencies]
arrow = "37.0.0"
byteorder = "1.4.3"
noodles = { version = "0.45.0", features = ["bam", "bcf", "bgzf", "core", "cram", "fasta", "fastq", "sam", "csi", "vcf", "tabix"] }
