[package]
name = 'r-oxbow'
version = '0.3.0'
edition = '2021'

[lib]
crate-type = ['staticlib']
name = 'oxbow'
doc = false

[dependencies]
extendr-api = '*'

oxbow = { workspace = true }
noodles = { workspace = true }
bigtools = { workspace = true }
flate2 = { workspace = true }
